### ISSUE TITLE
Can not use other precision than float32

### ISSUE THREAD

**Issue by RotemSap** [asappresearch/sru#102]
Hi!
Thank you so much for your implementation of the SRU.
We noticed that the input can not be in precision of float64, and we also suspect that no other precision than float32 can be used.
 
we can not supply an error trace, but the error is caused by the fact that a variable named _scale_x_   is hard coded as float32 at the SRUcell class.

the exception that we caught is as the following:

> RuntimeError: expected backend CUDA and dtype Double but got backend CUDA and dtype Float.
 
this error occurred due to the following command: 
```python 
x_ptr = x.contiguous() * scale_x if scale_x is not None else x.contiguous()
```  
 which is line 511 in cuda_functional.py.

Is the demand that scale_x be float32 mandatory? or could this be changed to the default precision of pytorch to allow different precisions to be used?

Thank you :)

**Comment by taoleicn** [comment]
could you check if the issue is resolved now?

**Comment by LysSanzMoreta** [comment]
@taoleicn I have exactly the same problem, also in the new version (2.6)

Fixed with changing to:
```

    if amp_recurrence_fp16 and U.dtype == torch.float16:
        cast = torch.Tensor.half
    else:
        cast = torch.Tensor.double #changed from .float
```

at src/ops.py at elementwise_recurrence_gpu
