### ISSUE TITLE
SRU Cell memory leak

### ISSUE THREAD

**Issue by pratikgujjar** [asappresearch/sru#105]
Using just the SRU cell in a loop with attention multiplied inputs, causes memory used to expand every iteration.

Code:
s = torch.zeros(batch_size, HIDDEN_SIZE)
for f in range(MAX_ITER):
            alpha, u = self._get_alpha(f, s)
            x = self.fc1(u) + self.fc2(c)
            s, _ = self.sru_cell(x, c0=s) # This causes the memory leak
            o = self.fc3(u) + self.fc4(s)
            o = self.fc5(nn.Tanh()(o)) 
            outputs.append(o)

**Comment by taoleicn** [comment]
This is being fixed in https://github.com/asappresearch/sru/pull/171, currently in dev branch.
