### ISSUE TITLE
Can i put hidden states in sru cell forward like in vanilla pytorch?

### ISSUE THREAD

**Issue by hadaev8** [asappresearch/sru#118]
In vanilla it work like this
```
rnn = nn.LSTMCell(10, 20)
input = torch.randn(6, 3, 10)
hx = torch.randn(3, 20)
cx = torch.randn(3, 20)
output = []
for i in range(6):
    hx, cx = rnn(input[i], (hx, cx))
    output.append(hx)
```
How can i do same for sru cell?

**Comment by taoleicn** [comment]
Yes you can. Here is an example:
https://github.com/asappresearch/sru/blob/master/language_model/train_enwik8.py#L79

The usage is like:
`output, state = rnn(input, previous_state)`
or explicitly
`output, state = rnn(input, c0=previous_state)`

https://github.com/asappresearch/sru/blob/master/sru/sru_functional.py#L348

**Comment by hadaev8** [comment]
@taoleicn 
Should you advise, how can I use SRU class for train and SRU or SRUCell for autoregressive interference?
Using SRUCell should be ineffective for train, right?

**Comment by hadaev8** [comment]
@taoleicn 

Should be sru cell example looks like this?

input = torch.randn(6, 3, 10)
cx = torch.randn(3, 20)
output = []
for i in range(6):
    hx, cx = rnn(input[i], cx)
    output.append(hx)

**Comment by taoleicn** [comment]
@hadaev8 you don't need to use the for loop here. It will be slow. 
SRUCell takes care of it for you. Just do:
```
input = torch.randn(6, 3, 10)  # length: 6, batch size: 3, d: 10
cx = torch.randn(3, 20)
output, new_cx = SRUCell(input, cx)
```
output will be a tensor of output hidden states, with size = (length, batch_size, output_hidden_size)

**Comment by hadaev8** [comment]
@taoleicn 
Well, it is for decoder.
I tried to compare performance with lstmcell.
But encountered a memory leak.
https://github.com/asappresearch/sru/issues/69
As I understand, it makes sense to use sru only in the encoder.

**Comment by taoleicn** [comment]
Well. You still don't need to use the for loop and can train SRU for decoder (autoregressive model).
The language model examples should already show how to do that:
https://github.com/asappresearch/sru/tree/master/language_model

These examples are no different to those using LSTM / GRU to be honest.

**Comment by hadaev8** [comment]
@taoleicn 
My attention calucaletes recurcivelly.
I will try to check if it can be calculated in parallel.
Thanks.
