### ISSUE TITLE
failed when optimizing model with torchscript

### ISSUE THREAD

**Issue by LearnedVector** [asappresearch/sru#123]
Hello! thanks for the repo. I tried to optimize the model using torchscript and it fails. is there any support for freezing the graph with `torch.jit.trace` function?

**Comment by taoleicn** [comment]
hi @LearnedVector ,

Are you trying to do this for production e.g. using the model in C++? We have a plan to explore this later this year.

**Comment by LearnedVector** [comment]
Correct! Trying to use this for production but not necessarily in c++. Just want a simple JIT traced model so I can import the model to production environment without having to port the model code. And good to know it’s being worked on

**Comment by taoleicn** [comment]
@LearnedVector 
The master branch and `sru >= 2.4.1` are now torchscript compatible.

**Comment by LearnedVector** [comment]
awesome!
