### ISSUE TITLE
Error unpacking PackedSequence on latest version

### ISSUE THREAD

**Issue by bratao** [asappresearch/sru#128]
Hello @taolei87 , 
After updating to the latest version, my code broke. It works great on the previous 2.3.5 version and with nn.LSTM.

  ```
File "C:\xxx\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\xxx\lib\site-packages\sru\modules.py", line 576, in forward
    mask_pad = (mask_pad >= batch_sizes.view(length, 1)).contiguous()
RuntimeError: shape '[393, 1]' is invalid for input of size 384
```

I can see that in the previous version the unpacking code on forward was different:
```
        input_packed = isinstance(input, nn.utils.rnn.PackedSequence)
        if input_packed:
            input, lengths = nn.utils.rnn.pad_packed_sequence(input)
            max_length = lengths.max().item()
            mask_pad = torch.ByteTensor([[0] * l + [1] * (max_length - l) for l in lengths.tolist()])
            mask_pad = mask_pad.to(input.device).transpose(0, 1).contiguous()
```

Now is:
```

        orig_input = input
        if isinstance(orig_input, PackedSequence):
            input, batch_sizes, sorted_indices, unsorted_indices = input
            length = input.size(0)
            batch_size = input.size(1)
            mask_pad = torch.arange(batch_size,
                                    device=batch_sizes.device).expand(length, batch_size)
            mask_pad = (mask_pad >= batch_sizes.view(length, 1)).contiguous()
```

**Comment by taoleicn** [comment]
hi @bratao i can take a look into this. 
Would you mind sharing the pytorch version and a toy example of inputs to SRU for me to reproduce the error?

**Comment by bratao** [comment]
Thank you @taolei87 
I´m doing a very regular training using AllenNLP, but using SRU in place of a LSTM.

I attached an example. Sorry for the laziness, but I torch.saved the mask and input. 

I´m in Windows 10 x64, Python 3.8 and Pytorch 1.6
[test_sru.zip](https://github.com/asappresearch/sru/files/5234815/test_sru.zip)

**Comment by bratao** [comment]
@taolei87 that example I sent in the last post is enough to you? If you prefer I can try to do without using serialized tensors.

**Comment by taoleicn** [comment]
@bratao I revert this piece of code back to that of vesrion < 2.3.5. 
https://github.com/asappresearch/sru/pull/130

can you check if this PR works now?

**Comment by bratao** [comment]
@taolei87 yes, I can confirm. Everything is working great!! Thanks

**Comment by bratao** [comment]
@taolei87 please remember to release 2.4.2 in pypi! ❤️

**Comment by hadaev8** [comment]
Same here

**Comment by taoleicn** [comment]
Just made a new release.
