### ISSUE TITLE
should tensorboardX be listed as dependency? 

### ISSUE THREAD

**Issue by suliuzh** [asappresearch/sru#133]
Hi
I am wondering if **tensorboardX** should be listed in requirements,txt?
As we can see, **tensorboardX**  is used in _sru/language_model/train_enwik8.py_ as a must. But when I use "pip install sru", it seems that tensorboardX will not be installed automatically. So should  **tensorboardX** be listed as dependency?
![image](https://user-images.githubusercontent.com/27858725/94336830-9db48280-0018-11eb-8df3-5d57654a12d4.png)

**Comment by taoleicn** [comment]
Hi @suliuzh ,

Thank you for the comments. SRU doesn't require tensorboardX to run so it shouldn't be a package dependency in my opinion. The examples of various NLP tasks can have additional dependencies needed to run. I can put extra `requirements.txt` in the sub-folders.
