### ISSUE TITLE
module: radam is not found

### ISSUE THREAD

**Issue by snaik2016** [asappresearch/sru#170]
It is available in keras_radam do you also need tensorflow

**Comment by taoleicn** [comment]
@snaik2016 thank you. 
you can install `radam` from the original repo as well: https://github.com/LiyuanLucasLiu/RAdam I did `pip install -e .` from the cloned repo directory. also only `pip install tensorboardx` is needed.

I'll update the README with these extra dependencies.

**Comment by snaik2016** [comment]
Thanks this worked we can close this issue.
