### ISSUE TITLE
possible typo at ValueError statement in modules.py

### ISSUE THREAD

**Issue by dave-rtzr** [asappresearch/sru#178]
Hi, I am currently reading the code of SRUpp, and it seems to me there is a typo at a ValueError statement for sanity check.
The line number is 1157 of modules.py at 3.0.0 dev branch
```python
if input_size != self.input_size:
            raise ValueError("Input has size (*, *, {}) but expect a last dimension of {}".format(
                input_size, self.input_to_hidden
            ))
```
Since self.input_to_hidden is defined to be a torch.nn.Linear, it would print out specifications of that layer, but I feel self.input_size is more appropriate.

Thanks in advance

**Comment by taoleicn** [comment]
Thank you @dave-rtzr. I'll fix this typo in the next release.
