### ISSUE TITLE
Can you share the pre-trained SRU++ models?

### ISSUE THREAD

**Issue by huchinlp** [asappresearch/sru#179]
Hi,

SRU++ is very interesting and powerful!

I am looking forward to reproduce the reported results.
It will be much easier if you can provide the pre-trained models.

Thank you!

**Comment by taolei87** [comment]
hi @huchinlp 
Thank you for being interested in this work. 
I'll upload the model state_dict as soon as possible. Let me get back to you once that's done. Being on vacation this week.

**Comment by taoleicn** [comment]
@huchinlp 
The pre-trained models are uploaded:
https://github.com/asappresearch/sru/tree/3.0.0-dev/experiments/srupp_experiments
Let me know if there's any problem downloading the models.

**Comment by huchinlp** [comment]
Thanks so much!
I will try it ASAP.

taoleicn ***@***.***> 于2021年4月14日周三 下午11:11写道：

**Comment by huchinlp** [comment]
I tested these models on a 1080 Ti.
Here are the results.

1. base model
13219.7 tok/sec. 217645.0 tokens.
14060.3 tok/sec. 245568.0 tokens.
dev_ppl=17.500  test_ppl=18.253

2. large model 
9765.5 tok/sec. 217645.0 tokens.
10214.8 tok/sec. 245568.0 tokens.
dev_ppl=16.419  test_ppl=17.130

3. large model + k=5
13893.9 tok/sec. 217645.0 tokens.
14852.0 tok/sec. 245568.0 tokens.
dev_ppl=16.602  test_ppl=17.296

> @huchinlp
> The pre-trained models are uploaded:
> https://github.com/asappresearch/sru/tree/3.0.0-dev/experiments/srupp_experiments
> Let me know if there's any problem downloading the models.

**Comment by taoleicn** [comment]
@huchinlp Thanks for testing them. The results look consistent with what I got and report. :)
