### ISSUE TITLE
cannot import name 'SRU'

### ISSUE THREAD

**Issue by hangcao1004** [asappresearch/sru#180]
After 'pip install sru', I ran the examples, but the following error occurred：
Traceback (most recent call last):
  File "test/sru.py", line 2, in <module>
    from sru import SRU, SRUCell
  File "/home/caohang/test/sru.py", line 2, in <module>
    from sru import SRU, SRUCell
ImportError: cannot import name 'SRU'

I have tried a lot, but it doesn't work. Can you give me some help?

**Comment by taoleicn** [comment]
@hangcao1004 can you paste the full stack trace / error messages?

**Comment by hangcao1004** [comment]
Thanks，I have solved it by export /path/sru
