### ISSUE TITLE
Inference memory leak?

### ISSUE THREAD

**Issue by lxsyz** [asappresearch/sru#204]
Hello
When I use the sru model under the dev-3.0 branch for inference, I find that the memory keeps growing, is it because of memory leaks?
The code is simple
```
sru_left,_ = self.sru_left(input_left)
sru_right,_ = self.sru_right(input_right)
```
And I use `memory_profiler` to detect memory. The following code will result in a larger memory growth.
`h, c = rnn(prevx, c0_[i], mask_pad=mask_pad)`

Can you help me?

**Comment by wangxiao-star** [comment]
Your code doesn't report any errors？

**Comment by lxsyz** [comment]
> Your code doesn't report any errors？

No errors, and I run my code in cpu. Torch 1.6.0. 
I have also tried lstm model, it seems that if I call the model all the time, memory will grow over time.

**Comment by wangxiao-star** [comment]
你没有用GPU跑吗？
