### ISSUE TITLE
Increasing GPU Usage each epoch

### ISSUE THREAD

**Issue by santiag0m** [asappresearch/sru#69]
I'm trying to implement a model that includes a SRUCell. This are my specs:

Tesla M60 GPU
torch.__version__: 0.4.1.post2
torch.cuda.version: 9.0.176

Although its training, every epoch the memory usage in the GPU increases until it fills it. I made a toy example where this error occurs:

```python
import torch
from torch.autograd import Variable
from sru import SRUCell


batch_size = 5
seq_len = 60
epochs = 1000
cuda = torch.cuda.is_available()

model = SRUCell(100, 100)

if cuda:
    model.cuda(0)

optimizer = torch.optim.Adam([
        {'params':model.parameters()}], lr=1e-3)

loss_function = torch.nn.MSELoss()
    
seq = Variable(torch.rand(batch_size,seq_len,100))
y = Variable(torch.rand(batch_size,100))


if cuda:
    seq = seq.cuda(0)
    y = y.cuda(0)


model.train()

for e in range(epochs):
    model.zero_grad()
    
    h = Variable(torch.zeros(batch_size, 100))
    c = Variable(torch.zeros(batch_size, 100))
    
    if cuda:
        h = h.cuda(0)
        c = c.cuda(0)
    
    for i in range(seq_len):
        x = seq[:,i,:]
        h, c = model(x, c)
    loss = loss_function(h, y)
    loss.backward()
    optimizer.step()
    print('Epoch: {} - Loss: {}'.format(e, loss))
```

**Comment by taolei87** [comment]
Hi, 

Did you get an "out of memory" at the end?  If not, it's just a pytorch thing -- it doesn't free the memory immediately so you may see the process eating memory.

Also, you shouldn't use the `for i in range()` loop to iterate over each word in the sequence. This wouldn't give u any parallelization benefit / speedup. Instead, simply do `h, c = model(seq)`. See  https://github.com/taolei87/sru#examples or example model code provided as part of the repo.

**Comment by santiag0m** [comment]
Thanks,

I do get the "out of memory" error at the end, however using pytorch LSTMCell it does not happen.

This only happened with SRUCell, using the SRU for full sequences there was no problem, however I was planning to use intermediate outputs.

**Comment by taolei87** [comment]
That's interesting because SRU simply uses SRUCell. 

Did you remove the `for i in range()` loop and feed the entire batch to SRUCell() and SRU()?

**Comment by santiag0m** [comment]
No, I fed the entire batch sequence to SRU() (without a for loop) and it works perfectly, I haven't tested SRUCell() with complete sequences yet.

**Comment by erogol** [comment]
I'd second this issue. I try to replace GRU layers with SRU here https://github.com/mozilla/TTS. It works but it uses much more GPU memory and adds up more each epoch. 

I use PyTorch 1.2 
You can see the code here https://github.com/erogol/TTS_experiments/blob/SRU/layers/tacotron.py

**Comment by gvskalyan** [comment]
Hi @taolei87 ,

I have tested santiag0m's snippet for SRUCell by passing complete sequence and it is working fine without an increase in GPU memory. (to observe the change I have increased epochs from 1000 to 10000).
It works fine even for [LSTMCell](https://pytorch.org/docs/stable/nn.html#lstmcell) without increase in Memory.

Whereas for SRUCell it is increasing and it would eventually run out of Memory (OOM).

Why is SRUCell needed?
In seq2seq networks (encoder-decoder) architecture, in decoder side generation is [Auto-regressive](https://github.com/pytorch/fairseq/blob/d502958b4d3356c19e217bee834167b99a945423/fairseq/models/lstm.py#L473), it occurs for every token in seq_len and hence in case of recurrent units we [pass them through](https://github.com/pytorch/fairseq/blob/d502958b4d3356c19e217bee834167b99a945423/fairseq/models/lstm.py#L584) LSTMCell or GRUCell . [Reason to be used in decoder](https://stackoverflow.com/questions/57048120/pytorch-lstm-vs-lstmcell) .

Can you please help to find out why is this occuring? Thanks.

**Comment by hadaev8** [comment]
@gvskalyan 
Another use case for srucell recurrently is professor forcing training.
