### ISSUE TITLE
float16 handling

### ISSUE THREAD

**Issue by ywatanabe1989** [asappresearch/sru#98]
When I convert my model, which using this SRU unit, into float16 enabled one, it fails.
Is this SRU not implemented to use in float16 environment, or is it hard to fix it?

**Comment by taolei87** [comment]
Hi, I'm working on this PR and it should support it.

**Comment by taoleicn** [comment]
Closing this issue since SRU supports fp16 and amp now.

**Comment by visionscaper** [comment]
When I use Nvidia APEX for AMP, I get the following error:

```
File "/home/freddy/.virtualenvs/nuhame/lib/python3.7/site-packages/sru/modules.py", line 261, in forward
    h, c = self.apply_recurrence(U, V, residual, c0, scale_val, mask_c, mask_pad)
  File "/home/freddy/.virtualenvs/nuhame/lib/python3.7/site-packages/sru/modules.py", line 284, in apply_recurrence
    self.amp_recurrence_fp16)
  File "/home/freddy/.virtualenvs/nuhame/lib/python3.7/site-packages/sru/ops.py", line 139, in elementwise_recurrence_gpu
    mask_pad
  File "/home/freddy/.virtualenvs/nuhame/lib/python3.7/site-packages/sru/cuda_functional.py", line 83, in forward
    is_custom
RuntimeError: expected scalar type Half but found Float
```

I'm on SRI version `2.5.1`

Is there something specific I should do to use SRU with float16?

**Comment by visionscaper** [comment]
^ P.S. I tried with `amp_recurrence_fp16=True` and `False`

**Comment by taoleicn** [comment]
cc @hpasapp

**Comment by hpasapp** [comment]
Hi @visionscaper we support native pytorch AMP, we don't support Apex AMP. If you need to use APEX AMP, and are unable to migrate to pytorch native AMP, you will need to tweak the SRU code slightly, and ideally submit a PR with the changes. I'll go over what we did to make SRU work with pytorch native AMP, and then you can probably use that to create a PR to enable APEX AMP?

There are two main parts to be considered:
- a large matrix multiplication, using torch.mm.
- a custom recurrence kernel.

The large matrix multiplication seemed to work 'out of the box' in native AMP.

For the custom recurrence kernel, in native AMP, we did two things to get this to work inside an AMP `autocast` region:
     1. placed the call to the recurrence kernel inside a non-autocast region, https://github.com/asappresearch/sru/blob/1deeca9a3ae05bce4ac2e359490c46eb4aee464a/sru/ops.py#L99-L101
    2. prior to calling the recurrence kernel, cast all tensors either to all float16, or to all float32, https://github.com/asappresearch/sru/blob/1deeca9a3ae05bce4ac2e359490c46eb4aee464a/sru/ops.py#L102-L110

As you can see, the check for autocast, and the autocast disable, are pytorch native AMP specific. You will probably need to find an APEX AMP specific to way to handle these two things?

**Comment by hpasapp** [comment]
I'm going to close this issue since:
- SRU does now support fp16 (using native PyTorch AMP), which was the original topic of this issue, and
- we don't currently support APEX AMP (though PRs welcome)

**Comment by visionscaper** [comment]
Hi @hpasapp, thanks for the fast response. I will first try to move to native AMP, it's the future anyway.

**Comment by hpasapp** [comment]
@visionscaper Awesome! Sounds good :)

**Comment by hpasapp** [comment]
Great! :)
